# PlayerDeathMsgJp v2.0.0

# Output to server.log
loggingDeathMessage: false

# Suppress death message exclude OPs.
suppressDeathMessage: false

# Append world name to prefix.
prefixWorld: true
